### ISSUE TITLE
报错"修改状态: invalid token"

### ISSUE THREAD

**Issue by Blink1024** [mixool/mimotion#4]
脚本目录下运行
`bash mimotion.sh xx******xxx@mypassword@20000-22000 >> 刷步数.log 2>&1`
日志
xxxx年 x月 x日 星期x xx:xx:xx CST 小米运动账号 xx******xxx 步数 2xxxx 修改状态: invalid token

**Comment by mixool** [comment]
密码错误？ 
没注意 我好久没手动去领豆子了
